name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  PYTHON_VERSION: "3.11"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Use Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Bikeshed
        run: pip install bikeshed --quiet

      - name: Build documentation
        run: |
          mkdir docs
          cp uml.png docs/
          cp 'DCAT-AP-LT metaduomen킬 k큰rimo eiga pagal IS gyvavimo ciklo stadijas v2.0.1.pdf' docs/
          bikeshed spec index.bs docs/index.html
          bikeshed spec hvd.bs docs/hvd.html
          mkdir docs/en
          bikeshed spec index_EN.bs docs/en/index.html
          bikeshed spec hvd_EN.bs docs/en/hvd.html
      - name: Build v2.0
        run: |
          mkdir docs/v2.0
          cp uml.png docs/v2.0/
          cp 'DCAT-AP-LT metaduomen킬 k큰rimo eiga pagal IS gyvavimo ciklo stadijas v2.0.1.pdf' docs/v2.0/
          bikeshed spec v2.0/index.bs docs/v2.0/index.html
          bikeshed spec v2.0/hvd.bs docs/v2.0/hvd.html
          mkdir docs/v2.0/en
          bikeshed spec v2.0/index_EN.bs docs/v2.0/en/index.html
          bikeshed spec v2.0/hvd_EN.bs docs/v2.0/en/hvd.html

      - name: Upload UI artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
